services:
  - type: web
    name: volleyball-tournament
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080 # Render dynamically assigns ports, but defaults to this if we rely on their environment logic
